name: chipseq-automation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.27.1
  - bioconductor-chipseeker=1.18.0
  - bioconductor-genomicranges=1.34.0
  - bioconductor-org.hs.eg.db=3.7.0
  - bioconductor-rtracklayer=1.42.1
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.4.0
  - bowtie2=2.3.5
  - deeptools=3.2.1
  - deeptoolsintervals=0.1.7
  - fastqc=0.11.8
  - macs2=2.1.2
  - numpy=1.16.3
  - numpy-base=1.16.3
  - python=2.7.15
  - r-base=3.5.1
  - r-tidyverse=1.2.1
  - r-getopt=1.20.3
  - samtools=1.9
  - sra-tools=2.9.1_1
